# Generated by Django 5.1.3 on 2024-12-24 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kabbadi',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('dept_no', models.IntegerField(unique=True)),
                ('nation', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateTournament',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='India', max_length=100)),
                ('places', models.CharField(choices=[('India', 'India'), ('Abroad', 'Abroad')], default='India', max_length=6)),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kabbadi')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20, null=True)),
                ('player_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(38)])),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kabbadi')),
            ],
        ),
    ]
